output "office-pet" {
  description = "Name generated by random_pet."
  value       = random_pet.office.id
}

output "audit-entry" {
  description = "Content read back from the file written by the null_resource."
  value       = data.local_file.audit_entry.content
}
